# Generated by Django 5.0.9 on 2024-11-29 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddit',
            name='established_at',
        ),
    ]
