# Generated by Django 5.0.9 on 2024-12-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0002_remove_subreddit_established_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subreddits', models.ManyToManyField(blank=True, to='subreddit.subreddit')),
            ],
        ),
        migrations.AddField(
            model_name='subreddit',
            name='topics',
            field=models.ManyToManyField(blank=True, to='subreddit.topic'),
        ),
    ]
