# Generated by Django 5.0.9 on 2024-12-02 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0003_alter_subreddit_description_alter_subreddit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddit',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subreddits',
        ),
        migrations.AddField(
            model_name='topic',
            name='probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subreddit.subreddit')),
                ('topics', models.ManyToManyField(blank=True, to='subreddit.topic')),
            ],
        ),
    ]
