# Generated by Django 5.0.9 on 2024-12-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0004_remove_subreddit_topics_remove_topic_subreddits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reddit_id',
            field=models.CharField(default=-1, max_length=255, unique=True),
        ),
    ]
