# Generated by Django 5.0.9 on 2024-12-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0005_post_reddit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reddit_id',
            field=models.CharField(default=-1, max_length=255),
        ),
    ]
