# Generated by Django 5.0.9 on 2024-12-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0007_alter_post_reddit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='posts',
            field=models.ManyToManyField(blank=True, to='subreddit.post'),
        ),
    ]
