# Generated by Django 5.0.9 on 2024-12-26 03:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0008_topic_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topics',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='selftext',
        ),
        migrations.AddField(
            model_name='post',
            name='probs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='topic_labeling_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, max_length=255, null=True, size=None),
        ),
    ]
