# Generated by Django 5.0.9 on 2024-12-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0009_remove_post_topics_rename_content_post_selftext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
