# Generated by Django 5.0.9 on 2024-12-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0010_alter_subreddit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
