# Generated by Django 5.0.9 on 2024-12-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0011_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reddit_id',
        ),
    ]
